name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: windows-latest
    steps:
      # Faz o checkout do repositório
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Importante para análise completa (não usar clone superficial)

      # (Opcional) Instala Java, pois o Sonar pode precisar
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Configura o .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      # Instala a ferramenta SonarScanner para .NET
      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      # Inicia a análise
      - name: SonarCloud Begin
        run: dotnet sonarscanner begin /k:"xLarsMc_Projeto-FullStack" ^
                                      /o:"projet-fullstack" ^
                                      /d:sonar.login="${{ secrets.SONAR_TOKEN }}" ^
                                      /d:sonar.host.url="https://sonarcloud.io"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Compila a solução .NET (ajuste o caminho do seu .sln)
      - name: Build
        run: dotnet build Backend/Solution/Solution.sln --no-incremental

      # Finaliza a análise e envia resultados ao SonarCloud
      - name: SonarCloud End
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
